import Head from 'next/head';
import React from 'react';
import { Sidebar } from '../sidebar/Sidebar';

interface Props {
	children: React.ReactNode;
}

export const DashboardLayout = ({ children }: Props): any => {
	return (
		<>
			<Head>
				<title>Postulation App</title>
				<meta name="description" content="Generated by Postulation App" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="flex w-[100%] flex-row">
					<div className="relative w-[30%] items-center justify-between rounded-lg bg-gray-800 p-4 text-white md:m-6 md:p-4 ">
						{/* <h1>Postulation App</h1> */}
						<Sidebar />
					</div>
					<div className="  relative h-screen w-[70%] items-center justify-between rounded-lg bg-yellow-500 p-4 text-white md:m-6 md:p-4">
						{children}
					</div>
				</div>
			</main>
		</>
	);
};
