import Head from 'next/head';
import React from 'react';
import { Sidebar } from '../sidebar/Sidebar';

interface Props {
	children: React.ReactNode;
}

export const DashboardLayout = ({ children }: Props): any => {
	return (
		<>
			<Head>
				<title>Postulation App</title>
				<meta name="description" content="Generated by Postulation App" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="flex w-[100%] flex-row md:w-[100%]">
					<div className=" hidden bg-gray-800 p-4  text-white md:p-4 lg:relative lg:m-6 lg:block lg:w-[30%] lg:items-center lg:justify-between lg:rounded-lg ">
						<Sidebar />
					</div>
					<div className=" w-full  bg-gray-800 p-4 text-white md:relative md:m-6 md:h-screen md:w-[70%] md:items-center md:justify-between md:rounded-lg md:p-4">
						{children}
					</div>
				</div>
			</main>
		</>
	);
};
