/* eslint-disable @typescript-eslint/strict-boolean-expressions */
import tokenAuth from '@/api/tokenAuth';
import { useAppDispatch } from '@/hooks/redux';
import { checkAuth } from '@/store/authentication/authenticationSlice';
import Cookies from 'js-cookie';
import Head from 'next/head';
import React, { useEffect } from 'react';

interface Props {
	children: React.ReactNode;
}

export const MainLayout = ({ children }: Props): any => {
	const dispatch = useAppDispatch();

	useEffect(() => {
		const token = Cookies.get('token');
		if (token) {
			tokenAuth(token);
		}
		dispatch(checkAuth());
	}, []);

	return (
		<>
			<Head>
				<title>Postulation App</title>
				<meta name="description" content="Generated by Postulation App" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>{children}</main>
		</>
	);
};
