import Head from 'next/head';
import React from 'react';

interface Props {
	children: React.ReactNode;
}

export const NavBarLayout = ({ children }: Props): any => {
	return (
		<>
			<Head>
				<title>Postulation App</title>
				<meta name="description" content="Generated by Postulation App" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>{children}</main>
		</>
	);
};
